# Generated by Django 3.0.6 on 2020-05-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_form_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=300)),
            ],
        ),
    ]
